name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Deploy Frontend (dist)
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ${{ secrets.REMOTE_PUBLIC_HTML_PATH }}/
          state-name: .ftp-deploy-sync-state-frontend.json

      - name: Deploy Backend (server)
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./server/
          server-dir: ${{ secrets.REMOTE_SERVER_PATH }}/
          state-name: .ftp-deploy-sync-state-server.json
          exclude: |
            **/node_modules/**
            **/.env
            db.json
